image: docker:stable

options:
  docker: true

pipelines:
  branches:
    test_container:
      - step:
          caches:
            - node
          script:
            - apk update && apk add bash
            - export IMAGE_NAME=request-manager:$BITBUCKET_BUILD_NUMBER
            - ./bitbucket_scripts/setup.sh
            - ./bitbucket_scripts/build.sh
            - ./bitbucket_scripts/test.sh
            - ./bitbucket_scripts/deploy.sh
