image: docker:stable

options:
  docker: true

pipelines:
  branches:
    test_container:
      - step:
          caches:
            - node
          script:
            - apk add --no-cache nodejs
#            - npm install eslint eslint-config-airbnb-base eslint-plugin-import -g
#            - npm i lerna -g
#            - npm run setup
#            - npm run lint
#            - export IMAGE_NAME=$DOCKER_REGISTRY_DEV:$BITBUCKET_BUILD_NUMBER
            - export IMAGE_NAME=test
            - docker build -f ./docker/Dockerfile -t $IMAGE_NAME --build-arg SSH_PRIVATE_KEY="$(cat /opt/atlassian/pipelines/agent/data/id_rsa)" .
            - set -eu
            - apk add --no-cache py-pip bash
            - pip install --no-cache-dir docker-compose
            - docker-compose -v
            - npm run test:compose
#            - apt-get update
#            - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
#            - unzip awscli-bundle.zip -d /tmp/
#            - /tmp/awscli-bundle/install -b ~/bin/aws
#            - export PATH=~/bin:$PATH
#            - docker build -t $IMAGE_NAME --build-arg SSH_PRIVATE_KEY="$(cat /opt/atlassian/pipelines/agent/data/id_rsa)"  .
#            - eval $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
#            - docker push $IMAGE_NAME

