version: '3.3'
services:

    sut:
        image: $IMAGE_NAME
        container_name: sut
        depends_on:
            - sut-db
        environment:
            DATABASE_URL: postgres://postgres:secret@sut-db/stoxbcrm
        networks:
            - subsystems
        tty: true
        entrypoint: bash -c "lerna run test && lerna run test:integration"
        volumes:
          - ../packages:/services/packages
    sut-db:
        build:
            context: ../
            dockerfile: ./docker/db.Dockerfile
        container_name: sut-db
        networks:
            - subsystems
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: postgres
            POSTGRES_DB: stoxbcrm

networks:
    subsystems:
        driver: bridge
