version: '3.3'
services:

    sut-unit-tests:
        image: $IMAGE_NAME
        container_name: sut-unit-tests
        entrypoint: lerna run test

    sut-lint:
        image: $IMAGE_NAME
        container_name: sut-lint
        entrypoint: npm run lint

    sut-integration-tests:
        image: $IMAGE_NAME
        container_name: sut-integration-tests
        depends_on:
            - sut-db
        env_file:
            - ../docker/.env.test
        environment:
            DATABASE_URL: postgres://postgres:secret@sut-db/stoxbcrm
        networks:
            - subsystems
        tty: true
        entrypoint: lerna run test:integration

    sut-db:
        build:
            context: ../
            dockerfile: ./docker/db.Dockerfile
        container_name: sut-db
        networks:
            - subsystems
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: postgres
            POSTGRES_DB: stoxbcrm

networks:
    subsystems:
        driver: bridge
