version: '3.3'
services:

    sut:
        image: $IMAGE_NAME
        container_name: sut
        depends_on:
            - sut-db
        env_file:
            - ../docker/.env.test
        environment:
            DATABASE_URL: postgres://postgres:secret@sut-db/stoxbcrm
        networks:
            - subsystems
        tty: true
        entrypoint: lerna run test:integration
#            - npm run lint
#            - lerna run test
#            - lerna run test:integration

    sut-db:
        build:
            context: ../
            dockerfile: ./docker/db.Dockerfile
        container_name: sut-db
        networks:
            - subsystems
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: postgres
            POSTGRES_DB: stoxbcrm

networks:
    subsystems:
        driver: bridge
