version: '3.3'
services:

    request-manager-db:
        build:
            context: ../
            dockerfile: ./docker/db.Dockerfile
        container_name: stox-postgres-bc-rm
        ports:
            - 5434:5432
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: postgres
            POSTGRES_DB: stoxbcrm

    activemq:
        image: rmohr/activemq:5.14.5
        container_name: stox-activemq
        ports:
            - 61613:61613
            - 8161:8161

    dev-blockchain:
        image: arielstox/stox-dev-blockchain:1.0.1
        container_name: dev-blockchain
        ports:
            - 8545:8545
        volumes:
            - "/srv/bc-node/:/src/data:consistent"
