version: '3.3'
services:

    request-manager-db:
        build:
            context: ../
            dockerfile: ./docker/db.Dockerfile
        container_name: stox-postgres-bc-rm
        networks:
            - subsystems
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: postgres
            POSTGRES_DB: stoxbcrm

    activemq:
        image: rmohr/activemq:5.14.5
        container_name: stox-activemq
        networks:
            - subsystems
        ports:
            - 61613:61613

networks:
    subsystems:
        driver: bridge
